### ISSUE TITLE
How to get SmartConfig version?

### ISSUE THREAD

**Issue by KiraSu** [EspressifApp/EsptouchForIOS#1]

**Comment by EspressifApp** [comment]
Hi KiraSu,

I asked the related colleague just now. He said you could see the Smart Config version in the device’s log.

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China
