### ISSUE TITLE
请问其中的 ESPUDPSocketClient 怎么用

### ISSUE THREAD

**Issue by shaop** [EspressifApp/EsptouchForIOS#10]
我在代码中初始化了ESPUDPSocketClient 以及发送了相应的消息，但是没有地方接受返回消息，作者能麻烦在文档中写一下吗？谢谢了！

**Comment by afunx** [comment]
这里的ESPUDPSocketClient，就是发送UDP数据报，不接收数据的啊。

**Comment by shaop** [comment]
那请问哪里可以接受数据呢？

**Comment by EspressifApp** [comment]
这个接口就没有设计接收数据的呀。

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China
