### ISSUE TITLE
我想问一下是不是直接使用这个历程，就能让wifii 模块连接上路由器了，WIFI模块在SmartConfigure 模式下的话

### ISSUE THREAD

**Issue by Marcello168** [EspressifApp/EsptouchForIOS#18]

**Comment by afunx** [comment]
是的呢

**Comment by Marcello168** [comment]
你好,我再想问一个问题，就是，我Smart configure ，设备成功入网之后，我怎么知道 ，哪一些设备是8266 的IP呢。路由器上面有那么多的设备，虽然入网之后，设备是会返回对应的IP回来，但是别的手机如何知道这个IP 就是8266 使用的呢？有没有一键搜索这种功能呢，只要发送一个命令。只要是8266 的设备 都会返回对应的IP回来呢。感谢解答

**Comment by EspressifApp** [comment]
@Marcello168 
当8266设备连上路由器后想重新获取ip地址，可以在路由器下发送UDP广播 "Are You Espressif IOT Smart Device?"
8266设备收到该广播后就会将会以 "I'm device_type device_mac device_ip" 的形式进行回复

**Comment by Marcello168** [comment]
那只是返回ip 吗? 我还想知道能不能和Mac 地址一起返回呢？ 因为IP这个东西是会变动的呢

**Comment by Marcello168** [comment]
因为有些资料是存在手机本地的，需要根据mac 地址唯一标识码来用的呢，感谢解答

**Comment by EspressifApp** [comment]
@Marcello168 
返回设备类型 设备mac 设备ip三个信息

**Comment by Marcello168** [comment]
你好按照你说的 我这样子发送好像，没有返回呢？是不就是因为我固件是透传的问题呢？

    NSString *string = @"Are You Espressif IOT Smart Device?\r\n";
    NSData *data = [string dataUsingEncoding:NSUTF8StringEncoding];
    [self sendPackWithIP:@"255.255.255.255" packData:data];

**Comment by EspressifApp** [comment]
@Marcello168 
发送内容不需要"\r\n"

**Comment by EspressifApp** [comment]
@Marcello168 
还有忘了说了，设备端的UDP端口号是 1025

**Comment by Marcello168** [comment]
这个哪里有资料可以参考吗？或者有详细的文档吗？谢谢了。我明天按照你说的再试试看。

**Comment by afunx** [comment]
官网上有Demo，可以直接运行的

**Comment by Marcello168** [comment]
@afunx 能发个链接吗？我好像没看到官网的Demo 可以直接获取设备的IP 和Mac 地址的，无限感激

**Comment by Marcello168** [comment]
@EspressifApp 你好，我用的固件是AT 指令的固件，然后我用PC 的网络助手发送可以在路由器下发送UDP广播 "Are You Espressif IOT Smart Device?"发送端口用的是1025 ，发现没有返回你说的那个信息呢？这是啥原因呢？有没有可能是因为是AT 指令的固件，导致他没有这个功能呢？感谢解答

**Comment by Marcello168** [comment]
![wechatimg149](https://user-images.githubusercontent.com/20309676/31879353-c4d245ae-b80f-11e7-938f-16a32837ec75.jpeg)

**Comment by afunx** [comment]
这个和SmartConfig不是一个问题。具体你可以发邮件给espressif的技术支持工程师。我感觉有可能是你的Device状态不对。

**Comment by Marcello168** [comment]
@afunx 我知道这个不是SmartConfigure 的问题，我想知道的是，因为我是用的是AT 指令的固件，所以我进入了透传的模式后。不确定会不会影响局域网搜索设备的功能，谢谢解答

**Comment by afunx** [comment]
SmartConfigure和其他模式都不兼容。Device处于SmartConfigure模式时，只能做SmartConfig，其他任何事情都做不了。

**Comment by Marcello168** [comment]
@afunx 我想你误会我的意思了。我们现在的测试是，我在模块通过SmartConfigure入网之后，也就是SmartConfigure停止之后。去使用局域网搜索设备的功能，但是模块并没有返回相对应的信息，所以我想确认一下是不是我是用了透传的功能导致这样的后果的。PS（我们使用的是AT 版本的固件）谢谢解答

**Comment by afunx** [comment]
具体你去发邮件问espressif的技术支持吧。我对于AT版本的固件不了解呢。
