### ISSUE TITLE
Esptouch 的功能有没有封装好的框架文件或者是静态.a文件提供给IOS的开发者

### ISSUE THREAD

**Issue by keya777777** [EspressifApp/EsptouchForIOS#2]
如题

**Comment by EspressifApp** [comment]
暂时还没有。最近会更新一版支持IPv6 only的。之后，会新建一个github项目，提供.a文件的。

**Comment by EspressifApp** [comment]
新建项目[LibEsptouchForIOS](https://github.com/EspressifApp/LibEsptouchForIOS)，提供了封装好的静态.a文件。目前，还是使用的上次发布的v0.3.4.3。IPv6 only支持的.a，Device完成相关开发，经过联合测试后，会尽快发布。
