### ISSUE TITLE
ESPtouch v0.3.7.0 doesn't work on iOS 13.1

### ISSUE THREAD

**Issue by alf45tar** [EspressifApp/EsptouchForIOS#40]
It shows always SSD (W-Fi) and BSSD (00:00:00:00:00:00).

**Comment by fanbaoying** [comment]
![屏幕快照 2019-10-11 下午3 24 46](https://user-images.githubusercontent.com/24238160/66632546-4f597880-ec3b-11e9-946c-4b8ea99fc819.png)

**Comment by marosell** [comment]
So, what does this mean for the future of Esptouch?

**Comment by alf45tar** [comment]
They release a new version 2 days ago.
