### ISSUE TITLE
对esp8266配网在 ios15系统下失败

### ISSUE THREAD

**Issue by chuancqc** [EspressifApp/EsptouchForIOS#64]
我尝试使用了官网发布的APP-2.3.0/SDK1.1.0 app，在ios 14.7.1能够成功配网，但是使用ios15.0或ios15.1均无法成功配网，仅对esp8266而言，esp32系列能够正常配置。
自行编译了最新的代码并装机结果同上，望解答，多谢。

**Comment by chaoStrength** [comment]
我也遇到了同样的问题，请问你解决了吗？

**Comment by chuancqc** [comment]
> 我也遇到了同样的问题，请问你解决了吗？

目前为止并没有思路，我尝试了不同版本的8266设备端代码均未能成功。

**Comment by chaoStrength** [comment]
自动iOS14.5后，如果使用了最新的xcode编译器，那么1、需要在infoplist中增加本地权限Privacy - Local Network UsageDescription，2、去开发者网站将Multicast Networking权限打开（现在不需要申请了，可以直接打开）3、在Xcode entitlement中增加权限<key>com.apple.developer.networking.multicast</key><true/>，具体详情见这篇博文https://www.jianshu.com/p/c4b414262b6e ，由于需要硬件验证，现在硬件没在身边，等晚上回家我验证一下，你也可以尝试一下。

**Comment by chaoStrength** [comment]
iOS 14 通过通知人们何时有 App 要访问他们的本地网络，并让他们能随时阻止或撤销这类访问，从而让这些行为透明且可控。具体相关信息可以参考Apple官方说明：https://developer.apple.com/cn/news/?id=0oi77447，以及一篇博文：https://www.jianshu.com/p/c4b414262b6e

**Comment by chuancqc** [comment]
> iOS 14 通过通知人们何时有 App 要访问他们的本地网络，并让他们能随时阻止或撤销这类访问，从而让这些行为透明且可控。具体相关信息可以参考Apple官方说明：[https://developer.apple.com/cn/news/?id=0oi77447，以及一篇博文：https://www.jianshu.com/p/c4b414262b6e](https://developer.apple.com/cn/news/?id=0oi77447%EF%BC%8C%E4%BB%A5%E5%8F%8A%E4%B8%80%E7%AF%87%E5%8D%9A%E6%96%87%EF%BC%9Ahttps://www.jianshu.com/p/c4b414262b6e)
多谢，我正在阅读和尝试。

**Comment by chuancqc** [comment]
我遵循最新版本的ESP8266_RTOS_SDK Release v3.4开发环境重构了历史版本后，配网和其他功能正常连接能够正常使用，基于新版本代码库的配网流程较为稳定。
