### ISSUE TITLE
I cannot setup esp board when wifi's password contains '@' 

### ISSUE THREAD

**Issue by locbkit** [EspressifApp/EsptouchForIOS#7]
Hi team,

I have tried this project with IOS 9.3.4, but It's always return failed. 

I double check with android version and I can verify that the board works with android library ( https://github.com/EspressifApp/EsptouchForAndroid ) BUT not IOS.

Could you please help me resolve this issue?

Cheer!

**Comment by EspressifApp** [comment]
Hi Guy,

Could offer more details?

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by locbkit** [comment]
Hi Bai,

Thanks a lot for your quick response

I have an IoT project, It need mobile app can send credentials of a wifi to an ESP8266 board and make it connects the wifi. I used your library and got that: it works well with android but NOT for IOS.

Firstly, I have just clone your project "EsptouchForIOS" and test with some versions of IOS and these are my results:

1. IOS v8.2: it WORKS well, Iphone send ssid and password to the esp8266 board and the board can setting itself to make it connect to the wifi. 

2. IOS v9.3.3 or 9.3.4: It does NOT work. After I entered correct password and then tap on "confirm" ==> the app always shows an dialog say that "Esptouch fail"

There is any advance settings I need to do to make it works?

Thanks

**Comment by EspressifApp** [comment]
Hi locbkit,

My iPhone version is 9.2.1, it is ok.
To verify the issue you are encountering, I am downloading OS X EI Capitan.
Let me upgrading my Mac OS and downloading the newest Xcode. After that, I’ll borrow a phone v9.3.3 or v9.3.4 from my colleague.
I’ll reply you ASAP.
Thank you for report the issue.

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by locbkit** [comment]
Hi Bai,

Thanks a lot for your super quick response. I'm really appreciate that!

I have just double checked and realize that the ESPTouch does not work on **9.3.2**  and 9.3.4. So sorry for my mistook

Cheer!

**Comment by EspressifApp** [comment]
Hi locket,

I have tested iOS v9.3.4, it’s OK.

> I have just double checked and realize that the ESPTouch does not work on 9.3.2 and 9.3.4. So sorry for my mistook
> 


Do you mean it is OK as well?

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by locbkit** [comment]
No, it's NOT work.

Both versions 9.3.2 and 9.3.4 are NOT work


Cheer!

**Comment by EspressifApp** [comment]
Are them connected to the same Wi-Fi?

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by locbkit** [comment]
Hi Bai

I found root cause of this issue because my wifi's password contains a special character: "@"

Finally, It works well. Thanks in advance for your super response. I'm really appreciate that.

Thanks a lot of bunch
Loc

**Comment by EspressifApp** [comment]
Hi locbkit,

It’s my duty of job.

Thank you for telling me when password contains “@“, it will fail.

I will tell it to the relevant colleagues.

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by EspressifApp** [comment]
Hi locbkit,

My colleague has tested the router of ’TP Link’ , ’MI’ , ’Huawei’ , ‘Dlink’ , ’Tenda’.
He set SSID contains ‘@‘, iOS 9.3.3 and iOS 9.3.4 success rate are 90% above.

I have asked him to set password. He will give me the response later.

I think we need more information about your situation.
Could you offer more information about you router and its configuration?


Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by EspressifApp** [comment]
Hi locbkit,

My colleague has tested the password contains ‘@‘. It is ok as well.

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by ZefengAI** [comment]
HI，Bai

I am an iOS engineer and I do not have a lot background knowledge in embedded processors. Is that I have to get a ESP8266 connect to my local wifi so the demo app(ESPTouchForiOS) will work? What is more, CNCopySupportedInterfaceso is depreciated in iOS and I cannot get the SSID in the app. I am using latest Xcode and deploy target is 6.0, os system is EI Capitan

Thanks a lot

Zefeng

**Comment by EspressifApp** [comment]
Hi Zefeng,

I’m glad to help you.  

>  Is that I have to get a ESP8266 connect to my local wifi so the demo app(ESPTouchForiOS) will work?
> 
Yes. You should get a ESP8266 supporting smart config.


> What is more, CNCopySupportedInterfaceso is depreciated in iOS and I cannot get the SSID in the app.
> 

I don’t find another way to get SSID presently though CNCopySupportedInterfaces is deprecated.

I suppose that you are deploy the demo on Simulator instead of iPhone.
As my experience, the Simulator sharing the Mac’s Wi-Fi, but I can’t get its SSID either.


Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by ZefengAI** [comment]
你好，白先生非常感谢你这么快的回复我，关于SSID 的问题我找到解决方案了，需要给苹果发邮件来active 这个功能（native 环境下得到SSID），因该是处于安全考虑。我们老板将和机器人连接的project 暂时放下来了，不过相信在年底这个肯定是要重新来做的。我们公司是做扫地机器人的，在北美，估计最后应该会用到你们的芯片。谢谢邱泽峰 iOS developer | AI Incorporated Inc


-------- Original Message --------
Subject: Re: [EspressifApp/EsptouchForIOS] I cannot setup esp board when
wifi's password contains '@' (#7)

**Comment by EspressifApp** [comment]
嗯，好的。我也相信以后会有合作的机会的。

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by dilip907** [comment]
Hi team,

I have tried this project with IOS 12.4, but It's always return failed.

I am using this library.
( https://github.com/lou-lan/SmartConfig ).

getting response 
[isSuc: NO,isCancelled: NO,bssid: (null),inetAddress: (null)]

Could you please help me resolve this issue?

Cheer!
