### ISSUE TITLE
iOS 10.01版本无法正常运行程序

### ISSUE THREAD

**Issue by xuelianyin** [EspressifApp/EsptouchForIOS#8]
iOS 10.01版本程序无法进行广播，9.3.1可以广播

**Comment by EspressifApp** [comment]
Hi lianyin,

谢谢你反馈的问题。但是，这两天我在外地出差，未带mac book。
“十一”过后，我会着手处理这个问题的。

现在可否请你提供更多有价值的初步信息？（尽可能多提供，提供不了也没关系）
1. Esptouch使用的版本。
2. 路由器型号和配置。
3. 其它你认为比较重要的信息。

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China

**Comment by EspressifApp** [comment]
Hi lianyin,

非常抱歉，让您等了这么久。
之前，收到你的反馈后，我司的相关工程师使用了ios10.0.2（由ios 9.3直接升级到ios 10.0.2）进行测试，是可以配置的。我还以为是ios10.0.1的bug。

最近，我们使用了由ios10.0.1（当时就不能使用Esptouch）升级到ios10.0.2的iphone，依然不行。
经过研究发现，ios9直接升级到ios10.0.1的所有应用默认关闭所有网络权限，ios9直接升级到ios10.0.2的所有应用默认打开所有网络权限。但是，我们的Esptouch使用的都是底层的Socket函数，未使用Cocoa Touch框架。所以，未向用户申请Network权限。此时，无法收发UDP广播报，导致Esptouch无法成功。

现问题已解决，解决方法就是应用打开时，发送一个"https://8.8.8.8"的GET请求，就会向用户申请Network权限。若不小心未允许，可通过如下方式改变：
设置-->无线局域网-->使用无线局域网与蜂窝移动的应用(在所有Wi-Fi列表之后)-->选择相应应用-->打开权限

iOS Esptouch库的相关代码，会在本周更新。App Store内的app也会在本周提交审核。

Best regards,
Bai     白桦
Android Developer | Espressif Systems

www.espressif.com <http://www.espressif.com/>
Room 204, Building 2, 690 Bibo Road, Zhangjiang High-tech Park, Shanghai 201203, China
